# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kron', '0003_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kron.Project'),
            preserve_default=False,
        ),
    ]
