# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kron', '0004_script_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='script',
            name='script_id',
            field=models.CharField(default='', max_length=16),
        ),
    ]
