# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kron', '0006_auto_20170210_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='script',
            name='pipeline',
        ),
        migrations.AddField(
            model_name='job',
            name='dataset',
            field=models.CharField(default='d1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='pipeline',
            field=models.CharField(default='p1', max_length=100),
            preserve_default=False,
        ),
    ]
