# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kron', '0007_auto_20170210_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='kron.Project'),
            preserve_default=False,
        ),
    ]
